### ISSUE TITLE
v3.0.0 precompiled binaries for Windows have not been released

### ISSUE THREAD

**Issue by sounisi5011** [1History/1History#11]
Currently (2022-08-03), [the v3.0.0 release page](https://github.com/1History/1History/releases/tag/v0.3.0) does not haveprecompiled binaries for Windows.

![](https://user-images.githubusercontent.com/6049678/182579495-b5236cd1-985c-462a-b61a-5f53deb4e74a.png)

This is because [the automatic release was cancelled on GitHub Actions](https://github.com/1History/1History/actions/runs/2567373343).

**Comment by jiacai2050** [comment]
https://github.com/1History/1History/releases/tag/v0.3.1

Hi, sorry for my delay. v0.3.1 contains Windows binary.
