### ISSUE TITLE
Feature Request: Repopulate charts when you filter out a domain

### ISSUE THREAD

**Issue by tuxruffian** [1History/1History#13]
### Current Behavior:
When you click on a top 10 object it filters it out of the chart leaving it with the top 9

### Desired Behavior:
When you click on a top 10 object it filters it out of the chart and promotes the 11th ranked object so that their are still 10 in the chart.

**Comment by jiacai2050** [comment]
I haven’t thought of a way to allow both of them, current design seems more natural for me

**Comment by jiacai2050** [comment]
Closing since not active.
