### ISSUE TITLE
[Bug] URL is not wrapped within double quotes in the exported CSV

### ISSUE THREAD

**Issue by sounisi5011** [1History/1History#14]
If the URL contains commas (`,`), the number of columns in the exported CSV will be greater than 4. In most URLs, commas are [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding), so this does not cause problems.

However, there are exceptions. For example, [Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) contain commas. Commas in Data URLs are not percent-encoded, so URL columns in the exported CSV will contain commas as they are.

```csv
20xx-xx-xx 00:00:00,page title,https://example.com/foo/bar,0
20xx-xx-xx 01:00:00,page title,data:text/html,%3Ch1%3EHello%2C%20World%21%3C%2Fh1%3E,0
```

The second line of this CSV contains four commas, unintentionally increasing the number of columns to five.

[In standard CSV, values containing commas are wrapped with double quotes](https://www.ietf.org/rfc/rfc4180.txt). Therefore, I think that URLs containing commas in exported CSV files should also be wrapped within double quotes.

```csv
20xx-xx-xx 00:00:00,page title,https://example.com/foo/bar,0
20xx-xx-xx 01:00:00,page title,"data:text/html,%3Ch1%3EHello%2C%20World%21%3C%2Fh1%3E",0
```

Or, I think [TSV](https://www.iana.org/assignments/media-types/text/tab-separated-values) export should be supported as well. The possibility of tab characters being included in the URL should be infinitesimally small. So TSV would not cause this problem.

```tsv
20xx-xx-xx 00:00:00	page title	https://example.com/foo/bar	0
20xx-xx-xx 01:00:00	page title	data:text/html,%3Ch1%3EHello%2C%20World%21%3C%2Fh1%3E	0
```

**Comment by jiacai2050** [comment]
Sounds good to me

**Comment by sounisi5011** [comment]
Notes on exporting [RFC4180](https://www.ietf.org/rfc/rfc4180.txt) compliant CSV files:

+ If the value contains line breaks or double quotes, these values should also be enclosed in double quotes.

    Both characters are percent-encoded in most URLs. However, since percent encoding is not required, double quotes may also be included in URLs.

    Also, double quotes may be included in the page title. If URLs are enclosed in double quotes in the exported CSV file, then I would think that page titles containing double quotes should also be enclosed in double quotes.
+ If the value contains double quotes, each double quote should be escaped.

    Each double quote should be increased to two (`"` -> `""`). For example, the following values are:

    | title |
    | - |
    | `foo` |
    | `foo"bar` |
    | `bar,baz` |
    | `baz""qux` |
    | `"quux"` |
    | `foo"bar,baz""qux"` |

    will be written to the CSV as a string like this:

    ```csv
    title
    foo
    "foo""bar"
    "bar,baz"
    "baz""""qux"
    """quux"""
    "foo""bar,baz""""qux"""
    ```

---

However, RFC4180 is **not a CSV specification**. CSV has a history in which different implementations existed for each application without a specification. RFC4180 was defined in response to this, there are still many applications that do not conform to RFC4180. Therefore, there is no need to strictly conform to RFC4180.

Although, I think it is better to comply with RFC4180 as much as possible to include page titles with confusing values such as `"foo bar"` in the CSV.

**Comment by jiacai2050** [comment]
https://docs.rs/csv/latest/csv/ may help implementing this.

**Comment by sounisi5011** [comment]
I noticed this bug was fixed when I updated onehistory installed by Cargo. Thank you very much!
