### ISSUE TITLE
Feature Request: Activity Tab from History Master

### ISSUE THREAD

**Issue by MrCybertux** [1History/1History#21]
In history master there was a activity tab in witch a list with all calls to websites was listed:
![image](https://github.com/1History/1History/assets/67368875/a5919098-871d-4c81-808e-7cac5accda04)

I am missing that in 1History
![image](https://github.com/1History/1History/assets/67368875/7314f40f-af11-47b9-a786-04108d2b142d)

I use history master for work since we have to write down what was done in the work hours but History master keeps having problems with older stuff 1 Month plus so i would like to use 1 History for that
Could this be implemented?

**Comment by jiacai2050** [comment]
You can click the dot in Daily PV graph, it will open a new page with histories for that day
