### ISSUE TITLE
Can not build project

### ISSUE THREAD

**Issue by balroggg** [1History/1History#3]
```
$ cargo run
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.58-x86_64-unknown-linux-gnu' toolchain
```
May be change to 1.58.1 toolchain channel?

**Comment by jiacai2050** [comment]
It's already defined in https://github.com/1History/1History/blob/master/rust-toolchain.toml, it will download latest toolchain, don't work for you?

**Comment by balroggg** [comment]
Oh sorry, yes cargo could not set up the toolchain, the problem was in my `rustup` dir(broken hash maybe).

All good now.
