### ISSUE TITLE
Hello can you update this feature into history master

### ISSUE THREAD

**Issue by ZhaoKunLong** [1History/1History#7]
- Hello  大佬，两年之前就使用了你制作的 history master. 的插件。真的很棒 ，然后看到你又更新了新工具。所以过来尝鲜，测试一波。
- 想问问大佬，有没有可能，把这个功能也集成到 history master上。

**Comment by jiacai2050** [comment]
这两个工具功能是类似的，感觉没什么大的区别，只不过 history master 是浏览器插件，受限于浏览器 API 的限制，很多事情是做不了的。
